# Generated by Django 3.2.14 on 2022-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donor_id',
            field=models.ManyToManyField(blank=True, to='adp.Donor'),
        ),
    ]
