# Generated by Django 3.2.14 on 2022-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='current_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
