# Generated by Django 4.0.4 on 2022-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='charity',
        ),
        migrations.AddField(
            model_name='charity',
            name='donor',
            field=models.ManyToManyField(to='adp.donor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
