# Generated by Django 3.2.14 on 2022-07-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adp.charity')),
            ],
        ),
    ]
