# Generated by Django 3.2.14 on 2022-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='date_formed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='charity',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
