# Generated by Django 4.0.4 on 2022-07-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
