# Generated by Django 4.0.4 on 2022-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0002_alter_donor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='target_amount',
            field=models.IntegerField(choices=[(100000, '$100,000'), (200000, '$200,000'), (300000, '$300,000'), (400000, '$400,000'), (500000, '$500,000'), (700000, '$700,000'), (600000, '$600,000'), (800000, '$800,000'), (900000, '$900,000'), (1000000, '$1M+')], null=True),
        ),
    ]
