# Generated by Django 4.0.4 on 2022-07-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0003_beneficiaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaries',
            old_name='full_name',
            new_name='name',
        ),
    ]
