# Generated by Django 3.2.14 on 2022-07-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0003_auto_20220711_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='name',
            new_name='charity_name',
        ),
    ]
