# Generated by Django 4.0.4 on 2022-07-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0003_alter_charity_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
