# Generated by Django 4.0.4 on 2022-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0003_remove_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='charity',
        ),
        migrations.AddField(
            model_name='charity',
            name='donor',
            field=models.ManyToManyField(default=True, to='adp.donor'),
        ),
    ]
