# Generated by Django 4.0.4 on 2022-07-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0004_rename_full_name_beneficiaries_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiaries',
            new_name='Beneficiary',
        ),
    ]
