# Generated by Django 4.0.4 on 2022-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0004_rename_deadline_charity_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='donor',
            field=models.ManyToManyField(blank=True, to='adp.donor'),
        ),
    ]
