# Generated by Django 3.2.14 on 2022-07-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0005_rename_beneficiaries_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='donor',
            field=models.ManyToManyField(blank=True, to='adp.Donor'),
        ),
    ]
