# Generated by Django 4.0.4 on 2022-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0005_alter_charity_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donor_id',
        ),
        migrations.AddField(
            model_name='donations',
            name='donor_id',
            field=models.ManyToManyField(blank=True, to='adp.donor'),
        ),
    ]
