# Generated by Django 4.0.4 on 2022-07-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0007_remove_donations_type_of_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
