# Generated by Django 3.2.14 on 2022-07-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0007_auto_20220705_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='type_of_donation',
        ),
    ]
