# Generated by Django 4.0.4 on 2022-07-05 13:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0008_remove_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dz275mqsc/image/upload/v1654858776/default_nbsolf.png', max_length=255, verbose_name='image'),
        ),
    ]
